"""create table migrations

Revision ID: 05bd3c7fb05e
Revises: 4ff6cc6ce9cb
Create Date: 2024-11-27 01:01:16.552301

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '05bd3c7fb05e'
down_revision: Union[str, None] = '4ff6cc6ce9cb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
