"""update

Revision ID: 3f57f2c53f2c
Revises: a7bc8365fb90
Create Date: 2024-11-28 08:25:07.513505

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3f57f2c53f2c'
down_revision: Union[str, None] = 'a7bc8365fb90'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_team_member_role', table_name='team_member')
    op.create_index(op.f('ix_team_member_role'), 'team_member', ['role'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_team_member_role'), table_name='team_member')
    op.create_index('ix_team_member_role', 'team_member', ['role'], unique=True)
    # ### end Alembic commands ###
