"""update

Revision ID: 491b5ab3ee49
Revises: 05bd3c7fb05e
Create Date: 2024-11-27 08:04:02.006330

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '491b5ab3ee49'
down_revision: Union[str, None] = '05bd3c7fb05e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('subscription', 'payment_date',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('subscription', 'expiration_date',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.drop_constraint('subscription_subscription_type_key', 'subscription', type_='unique')
    op.create_index(op.f('ix_subscription_subscription_type'), 'subscription', ['subscription_type'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_subscription_subscription_type'), table_name='subscription')
    op.create_unique_constraint('subscription_subscription_type_key', 'subscription', ['subscription_type'])
    op.alter_column('subscription', 'expiration_date',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('subscription', 'payment_date',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    # ### end Alembic commands ###
