"""update

Revision ID: a7bc8365fb90
Revises: 7a2b3dca5338
Create Date: 2024-11-27 17:56:39.575142

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a7bc8365fb90'
down_revision: Union[str, None] = '7a2b3dca5338'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'project', 'user', ['owner_id'], ['id'])
    op.create_foreign_key(None, 'task_assignment', 'user', ['user_id'], ['id'])
    op.create_foreign_key(None, 'team_member', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'team_member', type_='foreignkey')
    op.drop_constraint(None, 'task_assignment', type_='foreignkey')
    op.drop_constraint(None, 'project', type_='foreignkey')
    # ### end Alembic commands ###
