"""update

Revision ID: fa6ee91c62c9
Revises: caff95776858
Create Date: 2024-11-27 08:11:52.263411

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fa6ee91c62c9'
down_revision: Union[str, None] = 'caff95776858'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('subscription', 'payment',
               existing_type=sa.NUMERIC(precision=5, scale=2),
               type_=sa.Numeric(precision=7, scale=2),
               existing_nullable=False)
    op.drop_index('ix_subscription_subscription_type', table_name='subscription')
    op.create_index(op.f('ix_subscription_subscription_type'), 'subscription', ['subscription_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_subscription_subscription_type'), table_name='subscription')
    op.create_index('ix_subscription_subscription_type', 'subscription', ['subscription_type'], unique=True)
    op.alter_column('subscription', 'payment',
               existing_type=sa.Numeric(precision=7, scale=2),
               type_=sa.NUMERIC(precision=5, scale=2),
               existing_nullable=False)
    # ### end Alembic commands ###
